
name: CI

on:
   push:
    branches:
    - master  
   pull_request:
    branches:
    - master
  
jobs:
  build:
      runs-on: ubuntu-latest
      timeout-minutes: 30
      
      steps:
         - uses: actions/checkout@3

         - name: Build dockerfile and run dockerfile
           run: |
            docker build . -t cypress-docker-app:v1
            docker run -d -p 8001:8040 pytest-docker-app:v1

         - name: Set up QEMU
           uses: docker/setup-qemu-action@v3
      
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3
      
         - name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
    
         - name: Build and push
           uses: docker/build-push-action@v6
           with:
             push: true
             tags: ${{ secrets.DOCKERHUB_USERNAME }}/cypress-pytest-app:v1
         
         - name: Set up Python 3.11
           uses: actions/setup-python@3
           with:
               python-version: "3.11"
           
         - name: Install dependies
           run: |
              python -m pip install --upgrade pip
              pip install pipenv
              pipenv install --system
              playwright install chromium
              
         - name: Run tests
           run: pytest
           
         - name: Deploy 🚀
           if: always()
           uses: JamesIves/github-pages-deploy-action@4.1.5
           with:
             branch: gh-pages
             folder: reports
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
